// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/botcafe/amibot': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/botcafe/amibot').default>>>>
    }
    '/api/botcafe': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/botcafe/index').default>>>>
    }
    '/api/botcafe/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/botcafe/post').default>>>>
    }
    '/api/bots/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bots/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bots/[id].patch').default>>>>
    }
    '/api/bots/count': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bots/count.get').default>>>>
    }
    '/api/bots/createmany': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bots/createmany.post').default>>>>
    }
    '/api/bots': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bots/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bots/index.post').default>>>>
    }
    '/api/conversations/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conversations/[id].get').default>>>>
    }
    '/api/conversations/messages/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conversations/messages/[id].get').default>>>>
    }
    '/api/conversations/messages/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conversations/messages/post').default>>>>
    }
    '/api/conversations/post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conversations/post').default>>>>
    }
    '/api/galleries/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/[id].patch').default>>>>
    }
    '/api/galleries/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/[name].get').default>>>>
    }
    '/api/galleries/count': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/count.get').default>>>>
    }
    '/api/galleries/createmany': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/createmany.post').default>>>>
    }
    '/api/galleries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/galleries/index.post').default>>>>
    }
    '/api/prisma': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prisma').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.put').default>>>>
    }
    '/api/users/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].patch').default>>>>
    }
    '/api/users/count': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/count.get').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
  }
}
export {}