POST https://api.openai.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{$dotenv OPENAI_API_KEY }}

  {
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "You are telling me a one-sentence creative, unpredictable and lovely dream in second person."}],
     "temperature": 1,
     "n": 2,
     "max_tokens": 40
   } 