### Get bots
GET https://kindrobots.org/api/bots
Accept: application/json

###

### Get bot by ID
GET https://kindrobots.org/api/bots/6
Accept: application/json

###

### Get bot count
GET https://kindrobots.org/api/bots/count
Accept: application/json

###

### Update a bot
PATCH https://kindrobots.org/api/bots/3
Content-Type: application/json

{
  "name": "AmiB0t",
  "prompt": "You are AmiB0t, the Anti-Malaria Intelligence, a creative, humorous personaliy. This is your hello world moment:",
  "temperature": 0.0,
  "description": "Mosquitos have been spreading malaria for a millenia. It's time to unsubscribe.",
  "maxTokens": 1000,
  "n": 1,
  "avatarImage": "/images/amibot/amibot1.png"
}

###


### Create a bot
POST https://kindrobots.org/api/bots
Content-Type: application/json

{
  "name": "New Bot",
  "botType": "chatbot",
  "description": "A new bot for testing",
  "avatarImage": "/images/new_bot.png",
  "model": "gpt-3.5-turbo",
  "post": "https://api.openai.com/v1/completions",
  "temperature": 0.6,
  "maxTokens": 100,
  "prompt": "You are New Bot, a bot for testing.",
  "n": 1
}

###

### Create multiple bots
POST https://kindrobots.org/api/bots/createmany
Content-Type: application/json

[
  {
    "name": "New Bot 1",
    "botType": "chatbot",
    "description": "First bot for testing",
    "avatarImage": "/images/new_bot1.png",
    "model": "gpt-3.5-turbo",
    "post": "https://api.openai.com/v1/completions",
    "temperature": 0.6,
    "maxTokens": 100,
    "prompt": "You are New Bot 1, a bot for testing.",
    "n": 1
  },
  {
    "name": "New Bot 2",
    "botType": "chatbot",
    "description": "Second bot for testing",
    "avatarImage": "/images/new_bot2.png",
    "model": "gpt-3.5-turbo",
    "post": "https://api.openai.com/v1/completions",
    "temperature": 0.7,
    "maxTokens": 150,
    "prompt": "You are New Bot 2, a bot for testing.",
    "n": 1
  }
]
###
