### Get bots
GET https://kindrobots.org/api/bots
Accept: application/json

###

### Get bot by ID
GET https://kindrobots.org/api/bots/1
Accept: application/json

###

### Get bot count
GET https://kindrobots.org/api/bots/count
Accept: application/json

###

### Update a bot
PATCH https://kindrobots.org/api/bots/3
Content-Type: application/json

{
  "name": "AmiB0t",
  "prompt": "You are AmiB0t, the Anti-Malaria Intelligence, a creative, humorous personaliy. This is your hello world moment:",
  "temperature": 0.0,
  "description": "Mosquitos have been spreading malaria for a millenia. It's time to unsubscribe.",
  "maxTokens": 1000,
  "n": 1,
  "avatarImage": "/images/amibot/amibot1.png"
}

###


### Create a bot
POST https://kindrobots.org/api/bots
Content-Type: application/json

{
  "name": "New Bot",
  "botType": "chatbot",
  "description": "A new bot for testing",
  "avatarImage": "/images/new_bot.png",
  "model": "gpt-3.5-turbo",
  "post": "https://api.openai.com/v1/completions",
  "temperature": 0.6,
  "maxTokens": 100,
  "prompt": "You are New Bot, a bot for testing.",
  "n": 1
}

###

### Create bots
POST https://kindrobots.org/api/bots
Content-Type: application/json

{
  "name": "New Bot",
  "botType": "chatbot",
  "description": "A new bot for testing",
  "avatarImage": "/images/new_bot.png",
  "model": "gpt-3.5-turbo",
  "post": "https://api.openai.com/v1/completions",
  "temperature": 0.6,
  "maxTokens": 100,
  "prompt": "You are New Bot, a bot for testing.",
  "n": 1
}

###
